### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by jbacule** [XiaoLin1995/vue-fortune-wheel#12]
Hi @XiaoLin1995, this component was great. I'm just wondering if this can support Vue 3? Thanks in advance.

**Comment by dathacky** [comment]
https://github.com/XiaoLin1995/vue-fortune-wheel/issues/13
@jbacule

**Comment by jbacule** [comment]
Awesome! Thanks for the update @dathacky.

**Comment by XiaoLin1995** [comment]
Already support vue3, please run `npm install vue-fortune-wheel@latest`
