### ISSUE TITLE
Mobile not working

### ISSUE THREAD

**Issue by Freakschnietz** [XiaoLin1995/vue-fortune-wheel#7]
Hey XiaoLin, 

I really love your fortune wheel. Great work. 
Unfortunately I have some trouble getting this work on mobile devices. Desktop works fine but my smartphone is not able to trigger the rotate-function. 

This is my code when i trigger @rotateStart:

...
  onCanvasRotateStart(rotate) {
      if (this.allowedToPlay === true) {
          rotate();
      }
  },
...

Any ideas about whats the issue? 

Thanks a lot,
Flo

**Comment by XiaoLin1995** [comment]
Hey Flo,

thank you for your support!
I'm sorry, the code you provided is not enough to know the reason. Can my demo works fine on your smartphone? If it can't works, can you tell me the chrome version of your smartphone’s browser, you can check it by running `console.log(window.navigator.userAgent)`. And you can use [Vconsole](https://github.com/Tencent/vConsole) to view console logs on your smartphone. You can also debug other issues on your smartphone by using Vconsole.

**Comment by Freakschnietz** [comment]
Awesome, I didn't know about Vconsole, looks great.

I think I just found the issue myself. 
Your demo works fine and i found out, that if I set the probability to a number with 4 decimal places (like 11.1111) it works on desktop, but not on mobile. So I set the probability to 11 for each field (and one on 12 for a wheel with 9 prizes) and it works like a charm :) 

Thanks for your fast reply.

**Comment by XiaoLin1995** [comment]
It can works fine on my iPhone and android when the probability is set to 4 decimal places.
```js
prizes: [
  {
    id: 1,
    name: 'Blue',
    value: 'Blue\'s value',
    bgColor: '#45ace9',
    color: '#ffffff',
    probability: 30.3333
  },
  {
    id: 2,
    name: 'Red',
    value: 'Red\'s value',
    bgColor: '#dd3832',
    color: '#ffffff',
    probability: 40.5556
  },
  {
    id: 3,
    name: 'Yellow',
    value: 'Yellow\'s value',
    bgColor: '#fef151',
    color: '#ffffff',
    probability: 29.1111
  }
]
```
